#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias g='git'
alias ga='git add'
alias gap='git add -p'
alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias gc='git commit --verbose'
alias gf='git fetch --all --prune'
alias git-rm-merged='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
